version: '2'
services:
  web:
    image: meatier_web
    ports:
    - "3000:3000"
    volumes:
    - .:/usr/src/app
    links:
    - rethinkdb
    env_file: .env
    command: npm start
  rethinkdb:
    image: rethinkdb
    ports:
    - "8080:8080"
    # - "28015:28015"
    # - "29015:29015"
    volumes:
    - .:/data
